networks:
  backend:
    driver: bridge
services:
  weather:
    build: .
    networks:
      - backend
    ports:
      - "8080:8080"

  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"
